% REFIT_SUBMDL_WITH_ADD_REGRESSORS
%
%   Refit the sum of exponential models to unit counts on electrodes with
%   the additional regressors of the animal's age and whether a probe is
%   new or used.
%% Parameters
P=get_parameters;
data_path = P.response_to_major_comment_3_submdl_data_path;
refit = false;
%% Fit the model or load results
if ~exist('Cells', 'var')
    load(P.Cells_path)
end
if ~isfile(data_path) || refit
    tic
    mdl_params = {  'N1_const', ...
                    'N1_AP', ...
                    'N1_ML', ...
                    'N1_age', ...
                    'N1_use', ...
                    'k_AP', ...
                    'k_DV_gtn2', ...
                    'k_SO', ...
                    'k_age', ...
                    'k_use'};
    S = sum_exp_trodes_select_mdl(Cells, 'Iterations', 10, ...10, ...
                                         'KFold', 5, ...
                                         'noise', 'poisson', ...
                                         'model_parameters', mdl_params);
    S = sum_exp_trodes_compute_CI(S, 'i_mdl', 1:5, 'n_boot', 1000); %1:5);
    toc
    save(data_path, 'S')
else
    load(data_path, 'S')
end
%% Plot
sum_exp_trodes_plot_coef(S, 'mdl_inds', 1:5, 'rescale', false)