Data = PB_analyze_NP_session('rec', 'T176_2018_06_19', ...
                             'group_by_area', {{'Cg1', 'M2'}, {'PrL'}}, ...
                             'plot_peth', false, ...
                             'plot_choice_modulation', false);