% COMPUTE_CHOICE_SELECTIVITY of units recorded from the same probe but in
% different animals
function [] = compute_choice_selectivity()
P = get_parameters;
if ~isfolder(P.choice_sel_data_path)
    error('Cannot find folder path')
end
for i = 1:numel(P.choice_sel_file_names)
    Cells_file_path = find_related_file(P.choice_sel_data_path, ...
                                        [P.choice_sel_file_names{i} ...
                                        '_Cells.mat'], ...
                                        'ignore_multiple', true);
    Trials_file_path = find_related_file(P.choice_sel_data_path, ...
                                        [P.choice_sel_file_names{i} ...
                                        '.Trials.mat'], ...
                                        'ignore_multiple', true);
    Cells_file_path=find_most_recent(Cells_file_path);
    Trials_file_path=find_most_recent(Trials_file_path);
    Cells{i} = load(Cells_file_path);
    S = load(Trials_file_path);
    if isfield(S, 'Trials')
        Trials{i} = S.Trials;
    else
        Trials{i} = S;
    end
end
%%
for i = 1:numel(P.choice_sel_file_names)
    vl_trials = ~Trials{i}.violated & ...
                  Trials{i}.responded & ...
                   Trials{i}.trial_type == 'a' & ...
                   Cells{i}.recorded{1};
    ChoiceMod{i} = PB_compute_choice_mod(Cells{i}, Trials{i}, ...
                                                   'compute_pval', false, ...
                                                   'ref', P.choice_sel_reference_event, ...
                                                   'steps_s', P.choice_sel_steps_s, ...
                                                   'bin_size_s',  P.choice_sel_bin_s, ...
                                                   'vl_trials', vl_trials);
end
save(P.choice_sel_mat_path,'ChoiceMod')