% make longevity plots

% requires the variable Cells in the workspace, which can be generated by
% "collect_cells_files"

%% plot the change in yield statistics over time separately by "recording configuration" (i.e. each unique combination of rat x probe x bank).
% this generates a figure with 8 subplots (4 rows and 2 columns).
% rows are
% 1. number of total units over time (SUs and MUs)
% 2. number of SUs over time
% 3. yield (SUs/channels) over time
% 4. average cell depth over time (change relative to first recorded session)

% the two columns contain the same data points but the recording
% configurations are colored by rat in the first column and by bank in the
% second column.

figure;
unique_banks = cellfun(@(x)x.unique_bank,Cells,'uni',1);
rats=unique(cellfun(@(x)x.rat,Cells,'UniformOutput',0));
rat_colors = distinguishable_colors(length(rats));
bank_colors = distinguishable_colors(2);
n_depths=2;
depth_colors = jet(n_depths);
unique_identifiers = unique(cellfun(@(x)x.identifier,Cells,'UniformOutput',0));
all_median_electrode_depth = cellfun(@(x)x.median_electrode_depth,Cells,'UniformOutput',1);       
quantiles = discretize(all_median_electrode_depth,n_depths);
clear k j l m
for i=1:length(unique_identifiers)
    for c=1:2
        current_sessions{i} = find(strcmp(cellfun(@(x)x.identifier,Cells,'UniformOutput',0),unique_identifiers{i}));
        current_bank(i) = str2num(unique_identifiers{i}(end));
        subplot(4,2,1+c-1);
        days_elapsed = cellfun(@(x)x.days_since_surgery,Cells(current_sessions{i}),'UniformOutput',1)+1;
        n_units = cellfun(@(x)x.n_units,Cells(current_sessions{i}),'UniformOutput',1);
        n_good_units = cellfun(@(x)x.n_good_units,Cells(current_sessions{i}),'UniformOutput',1);    
        n_electrodes_in_brain = cellfun(@(x)x.n_electrodes_in_brain,Cells(current_sessions{i}),'UniformOutput',1); 
        depth_quantile = quantiles(current_sessions{i}(1));

        mean_dv = cellfun(@(x)x.mean_DV,Cells(current_sessions{i}),'UniformOutput',1);            
        if c==1
            current_color = rat_colors(strcmp(rats,Cells{current_sessions{i}(1)}.rat),:);
        else
            current_color = bank_colors(current_bank(i)+1,:);
        end
        [days_elapsed,time_idx] = sort(days_elapsed);
        k(i) = plot(days_elapsed,n_units,'Color',current_color,'Marker','o','MarkerFaceColor',current_color,'LineWidth',2);hold on
        if i==length(unique_identifiers)
            legend(k,unique_identifiers);  
            set(gca,'xscale','log','yscale','log');    
            xlabel('Days Since Implant');ylabel('No. SU and MU');                
        end
        subplot(4,2,3+c-1);
        j(i) = plot(days_elapsed,n_good_units,'Color',current_color,'Marker','o','MarkerFaceColor',current_color,'LineWidth',2);hold on    
        if i==length(unique_identifiers)
            legend(j,unique_identifiers);    
            set(gca,'xscale','log','yscale','log');
            xlabel('Days Since Implant');ylabel('No. SU');        
        end
        subplot(4,2,5+c-1);
        l(i) = plot(days_elapsed,n_good_units./n_electrodes_in_brain,'Color',current_color,'Marker','o','MarkerFaceColor',current_color,'LineWidth',2);hold on    
        if i==length(unique_identifiers)
            legend(l,unique_identifiers);    
            set(gca,'xscale','log','yscale','log');
            xlabel('Days Since Implant');ylabel('Yield (units per channel)');
        end  
        subplot(4,2,7+c-1);
        m(i) = plot(days_elapsed - min(days_elapsed)+1,mean_dv - mean_dv(1),'Color',current_color,'Marker','o','MarkerFaceColor',current_color,'LineWidth',2);hold on    
        n_cells{i} = n_good_units;
        if i==length(unique_identifiers)
            legend(m,unique_identifiers);    
            set(gca,'xscale','log','yscale','linear');
            xlabel('Days Since First Recording');ylabel('Change in mean Cell Depth (mm below first recording)');
        end   
    end
end

%% plot change in mean cell depth for each session relative to the first session recorded for that configuration (as a scatter plot)
% depth change plot
figure;
elapsed = cat(2,m.XData);
delta_depth = cat(2,m.YData);
n_cells_all = cat(2,n_cells{:});
scatter(log10(elapsed),delta_depth,'SizeData',n_cells_all+1);
mdl = fitlm(log10(elapsed),delta_depth,'Weights',n_cells_all);
hold on;refline(mdl.Coefficients.Estimate(2),mdl.Coefficients.Estimate(1))

%% plot mean cell depth change with temporal binning, separately for bank 0 and bank 1.
figure;
n_time_bins=8;
bin_edges = [0.5 1.5 2.5 6.5 14.5 30.5 60.5 120.5 500];
for k=0:1
clear boots
in_bank = unique_banks==k;
for i=1:n_time_bins
    idx = elapsed>bin_edges(i) & elapsed<bin_edges(i+1);
    boots(:,i) = bootstrp(1000,@mean,delta_depth(idx(:) &  in_bank(:)   ));
end
t(k+1)=shadedErrorBar([bin_edges(1:n_time_bins) + bin_edges(2:n_time_bins+1)]/2,boots,{@mean,@std});hold on;
t(k+1).mainLine.LineWidth=2;
t(k+1).mainLine.Color = bank_colors(k+1,:);
t(k+1).patch.FaceAlpha=0.5;
t(k+1).patch.FaceColor = bank_colors(k+1,:);
set(gca,'xscale','log','yscale','linear','xlim',[1,mean(bin_edges(end-1:end))],'xtick',[1 10 50 100 200 300 400],'ylim',[-0.5 1]);
xlabel('Days Since First Recording');ylabel({'Change in mean Cell Depth','(mm below first recording)'});
end
legend([t.mainLine],{'Bank 0','Bank 1'});

%% plot total number of recorded SUs over time across sessions, with temporal binning, separately for banks 1 and 0.
% average no SUs over time
figure;
elapsed = cat(2,j.XData);
SUs = cat(2,j.YData);
n_time_bins=8;
bin_edges = [0.5 1.5 2.5 6.5 14.5 30.5 60.5 120.5 500];

for k=0:1
clear boots
in_bank = unique_banks==k;
for i=1:n_time_bins
    idx = elapsed>bin_edges(i) & elapsed<bin_edges(i+1);
    boots(:,i) = bootstrp(1000,@mean,SUs(idx(:) &  in_bank(:)   ));
end
t(k+1)=shadedErrorBar([bin_edges(1:n_time_bins) + bin_edges(2:n_time_bins+1)]/2,boots,{@mean,@std});hold on;
t(k+1).mainLine.LineWidth=2;
t(k+1).mainLine.Color = bank_colors(k+1,:);
t(k+1).patch.FaceAlpha=0.5;
t(k+1).patch.FaceColor = bank_colors(k+1,:);
set(gca,'xscale','log','yscale','log','xlim',[1,mean(bin_edges(end-1:end))],'xtick',[1 10 50 100 200 300 400],'ylim',[50 400]);
xlabel('Days Since Implant');ylabel('No. SU');        
end
legend([t.mainLine],{'Bank 0','Bank 1'});


% future plots

%% plot the longevity separately by depth (longevity in the 0-0.5DV group, the 0.5-1DV group, etc)

%% plot the longevity separately by brain area

%% plot event rate over time?
